-- CreateEnum
CREATE TYPE "NotificationType" AS ENUM ('LOAN_APPLICATION_SUBMITTED', 'LOAN_STATUS_UPDATE', 'LOAN_DISBURSEMENT_READY', 'LOAN_REPAYMENT_DUE', 'LOAN_REPAYMENT_RECEIVED', 'SAVINGS_UPDATE', 'ACCOUNT_UPDATE', 'GENERAL');

-- CreateTable
CREATE TABLE "Notification" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "type" "NotificationType" NOT NULL,
    "read" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Notification_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
